### ISSUE TITLE
Can't unfocus on mobile

### ISSUE THREAD

**Issue by Haroenv** [paypal/react-autocompletely#32] opened 2017-07-27 07:32 UTC
- `react-autocompletely` version:
- `node` version:
- `npm` (or `yarn`) version:

Relevant code or config

https://codesandbox.io/s/9rWEmzEv8

What you did:

Open it on an iPhone, try to press "done", but it doesn't dismiss the focusing 

What happened:

Input is permanently focused, not even the url bar is accessible. Can get the focus back out of it when pressing refresh only

Reproduction repository:

https://codesandbox.io/s/9rWEmzEv8

Problem description:

Suggested solution:

Allow the input to blur

**Comment by kentcdodds** [comment] 2017-07-27 07:52
I cannot reproduce this on my Android phone. Are you sure it's a problem? Maybe something it's only an ios issue?



![2017_07_27_00_49_57](https://user-images.githubusercontent.com/1500684/28659883-cb0a5a5a-7265-11e7-9b2e-ee5c60aede8c.gif)

**Comment by FezVrasta** [comment] 2017-07-27 08:14
I can reproduce it on iOS on both Chrome and Safari. The input seems to keep focus and the keyboard can't be closed.

**Comment by Haroenv** [comment] 2017-07-27 11:24
![2017-07-27 13_23_26](https://user-images.githubusercontent.com/6270048/28668150-de6ab680-72ce-11e7-9ca9-9c6110ea059a.gif)

Here's a reproducible example in the iOS simulator, might be related to how Safari deals with blurring?

**Comment by kentcdodds** [comment] 2017-07-27 15:30
Oh, that's odd. And that's how it works on iOS as well?

We definitely want to fix that! Could you dig into it a little bit?

**Comment by FezVrasta** [comment] 2017-07-27 15:53
I tested only on real device so I'd say "yes"

**Comment by dashed** [comment] 2017-07-27 17:07
Interesting. I can confirm this issue.

**Comment by kentcdodds** [comment] 2017-07-27 17:16
Alrighty! Who wants to fix it? :smile:

**Comment by psicotropicos** [comment] 2017-07-27 18:16
@kentcdodds I want 🤘

**Comment by dashed** [comment] 2017-07-28 02:23
I skimmed through this. The bug seems to be resolved when commenting this line out: https://github.com/paypal/react-autocompletely/blob/008129dca3da8ef7e118fd1bbc93c7cad55dc6d5/src/input.js#L77

When the input is blurred, `handleBlur` is called, which then calls `this.autocomplete.reset()`, which then calls `this.input.reset()`.

Im guessing `moveCursorToTheEnd` re-focuses the input element. On my iphone device, attempting to dismiss the input box actually flickers the keyboard (i.e. sliding down and back up). 

You can even see this in action in the gif at: https://github.com/paypal/react-autocompletely/issues/32#issuecomment-318335025

FYI, I debugged this in Safari.

-----

@kentcdodds what was the reason for moving the cursor to the end after resetting?

@psicotropicos I'm wondering if you've reached similar findings. Since you've called dibs on this, I'd let you PR this if this is the proper fix 👍

**Comment by psicotropicos** [comment] 2017-07-28 03:08
@dashed This was the same solution I found so far. 
I'm studying the rest of the code to understand the reason for moving the cursor to the end

**Comment by kentcdodds** [comment] 2017-07-28 03:50
You know, I think that we probably don't need that. At least not in the core library. People could implement it themselves if they need. Let's remove that code :+1: Thanks!

**Comment by kentcdodds** [comment] 2017-07-28 03:50
Who wants to do that?

**Comment by psicotropicos** [comment] 2017-07-28 04:20
I will send the PR

**Comment by psicotropicos** [comment] 2017-07-28 04:55
Done on #46 
Thank you very much @dashed 🤘

**Comment by kentcdodds** [comment] 2017-07-28 17:20
This has been fixed. I'll push another beta release as soon as I get the rest of the PRs merged.

**Closed** 2017-07-28 21:54 UTC
Labels: bug, help wanted
